version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: gomod
    directory: "/tests"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: gomod
    directory: "/utils/pcap_to_bytes"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: gomod
    directory: "/docs"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
