version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /tests
      - /utils/pcap_to_bytes
      - /docs
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: docker
    directories:
      - /
      - /cmd/external-dns
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - BeryJu
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
