name: "Setup"
description: Setup all Gravity test dependencies

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache: true
    - uses: actions/setup-node@v5
      with:
        node-version-file: web/package.json
        cache: "npm"
        cache-dependency-path: web/package-lock.json
    - shell: bash
      run: make web-install gen-client-ts web-build
    - shell: bash
      run: make test-env-start
    - shell: bash
      run: make install-deps gen-clean gen-client-go gen-external-dns gen-go-tidy
