---
version: '3.4'

services:
  gravity:
    # Important for this to be static and unique
    hostname: gravity1
    image: ghcr.io/beryju/gravity:latest
    restart: unless-stopped
    network_mode: host
    user: root
    volumes:
      - data:/data
    # The default log level of info logs DHCP and DNS queries, so ensure
    # the logs aren't filling up the disk
    logging:
      driver: json-file
      options:
        max-size": "10m"
        max-file": "3"

volumes:
  data:
    driver: local
