---
version: '3.4'

services:
  gravity:
    # Important for this to be static and unique
    hostname: gravity1
    image: ghcr.io/beryju/gravity:latest
    restart: unless-stopped
    network_mode: host
    user: root
    volumes:
      - data:/data

volumes:
  data:
    driver: local
