name: "Process test results"
description: Convert test results to JUnit, add them to GitHub Actions and codecov

inputs:
  flags:
    description: "codecov flags"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: make test-env-stop
    - shell: bash
      run: make test-convert
    - uses: test-summary/action@v2
      with:
        paths: ${{ github.workspace }}/junit.xml
        show: "fail"
    - uses: codecov/codecov-action@v5
      with:
        use_oidc: true
        flags: ${{ inputs.flags }}
        files: ${{ github.workspace }}/coverage.txt
    - uses: codecov/test-results-action@v1
      with:
        use_oidc: true
        flags: ${{ inputs.flags }}
        files: ${{ github.workspace }}/junit.xml
