all:
	wget -O undionly.kpxe http://boot.ipxe.org/undionly.kpxe
	wget -O netboot.xyz.kpxe https://boot.netboot.xyz/ipxe/netboot.xyz.kpxe
	wget -O netboot.xyz-undionly.kpxe https://boot.netboot.xyz/ipxe/netboot.xyz-undionly.kpxe
	wget -O netboot.xyz.efi https://boot.netboot.xyz/ipxe/netboot.xyz.efi
