// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: protobuf/role_tsdb_record.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricsRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRecord) Reset() {
	*x = MetricsRecord{}
	mi := &file_protobuf_role_tsdb_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRecord) ProtoMessage() {}

func (x *MetricsRecord) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_role_tsdb_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRecord.ProtoReflect.Descriptor instead.
func (*MetricsRecord) Descriptor() ([]byte, []int) {
	return file_protobuf_role_tsdb_record_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsRecord) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_protobuf_role_tsdb_record_proto protoreflect.FileDescriptor

const file_protobuf_role_tsdb_record_proto_rawDesc = "" +
	"\n" +
	"\x1fprotobuf/role_tsdb_record.proto\"%\n" +
	"\rMetricsRecord\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05valueB\x16Z\x14pkg/roles/tsdb/typesb\x06proto3"

var (
	file_protobuf_role_tsdb_record_proto_rawDescOnce sync.Once
	file_protobuf_role_tsdb_record_proto_rawDescData []byte
)

func file_protobuf_role_tsdb_record_proto_rawDescGZIP() []byte {
	file_protobuf_role_tsdb_record_proto_rawDescOnce.Do(func() {
		file_protobuf_role_tsdb_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_role_tsdb_record_proto_rawDesc), len(file_protobuf_role_tsdb_record_proto_rawDesc)))
	})
	return file_protobuf_role_tsdb_record_proto_rawDescData
}

var file_protobuf_role_tsdb_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_role_tsdb_record_proto_goTypes = []any{
	(*MetricsRecord)(nil), // 0: MetricsRecord
}
var file_protobuf_role_tsdb_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_role_tsdb_record_proto_init() }
func file_protobuf_role_tsdb_record_proto_init() {
	if File_protobuf_role_tsdb_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_role_tsdb_record_proto_rawDesc), len(file_protobuf_role_tsdb_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_role_tsdb_record_proto_goTypes,
		DependencyIndexes: file_protobuf_role_tsdb_record_proto_depIdxs,
		MessageInfos:      file_protobuf_role_tsdb_record_proto_msgTypes,
	}.Build()
	File_protobuf_role_tsdb_record_proto = out.File
	file_protobuf_role_tsdb_record_proto_goTypes = nil
	file_protobuf_role_tsdb_record_proto_depIdxs = nil
}
