[dev]
framework = "hugo"

[build]
publish = "public"
command = "hugo mod get && hugo --gc --minify"

[build.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.113.0"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/js/script.js"
  to = "https://plausible.io/js/plausible.outbound-links.js"
  status = 200
  force = true

[[redirects]]
  from = "/api/event"
  to = "https://analytics.beryju.io/api/event"
  status = 200
  force = true
