---
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 10.201.0.0/24

services:
  gravity-1:
    hostname: gravity-1
    container_name: gravity-1
    image: ghcr.io/beryju/gravity:latest
    restart: unless-stopped
    user: root
    environment:
      ADMIN_TOKEN: bootstrap-token
    networks:
      default:
        ipv4_address: 10.201.0.11
    ports:
      - 8008:8008 # webui
      - 8009:8009 # metrics
      - 8010:8010 # debug
    volumes:
      - data-1:/data
  gravity-2:
    hostname: gravity-2
    container_name: gravity-2
    image: ghcr.io/beryju/gravity:latest
    restart: unless-stopped
    user: root
    depends_on:
      - gravity-1
    environment:
      ETCD_JOIN_CLUSTER: bootstrap-token,http://10.201.0.11:8008
    networks:
      default:
        ipv4_address: 10.201.0.12
    volumes:
      - data-2:/data
  gravity-3:
    hostname: gravity-3
    container_name: gravity-3
    image: ghcr.io/beryju/gravity:latest
    restart: unless-stopped
    user: root
    depends_on:
      - gravity-2
    environment:
      ETCD_JOIN_CLUSTER: bootstrap-token,http://10.201.0.12:8008
    networks:
      default:
        ipv4_address: 10.201.0.13
    volumes:
      - data-3:/data

volumes:
  data-1:
    driver: local
  data-2:
    driver: local
  data-3:
    driver: local
