/*
gravity

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.28.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the EtcdAPIMemberJoinOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EtcdAPIMemberJoinOutput{}

// EtcdAPIMemberJoinOutput struct for EtcdAPIMemberJoinOutput
type EtcdAPIMemberJoinOutput struct {
	EtcdInitialCluster *string `json:"etcdInitialCluster,omitempty"`
}

// NewEtcdAPIMemberJoinOutput instantiates a new EtcdAPIMemberJoinOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEtcdAPIMemberJoinOutput() *EtcdAPIMemberJoinOutput {
	this := EtcdAPIMemberJoinOutput{}
	return &this
}

// NewEtcdAPIMemberJoinOutputWithDefaults instantiates a new EtcdAPIMemberJoinOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEtcdAPIMemberJoinOutputWithDefaults() *EtcdAPIMemberJoinOutput {
	this := EtcdAPIMemberJoinOutput{}
	return &this
}

// GetEtcdInitialCluster returns the EtcdInitialCluster field value if set, zero value otherwise.
func (o *EtcdAPIMemberJoinOutput) GetEtcdInitialCluster() string {
	if o == nil || IsNil(o.EtcdInitialCluster) {
		var ret string
		return ret
	}
	return *o.EtcdInitialCluster
}

// GetEtcdInitialClusterOk returns a tuple with the EtcdInitialCluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EtcdAPIMemberJoinOutput) GetEtcdInitialClusterOk() (*string, bool) {
	if o == nil || IsNil(o.EtcdInitialCluster) {
		return nil, false
	}
	return o.EtcdInitialCluster, true
}

// HasEtcdInitialCluster returns a boolean if a field has been set.
func (o *EtcdAPIMemberJoinOutput) HasEtcdInitialCluster() bool {
	if o != nil && !IsNil(o.EtcdInitialCluster) {
		return true
	}

	return false
}

// SetEtcdInitialCluster gets a reference to the given string and assigns it to the EtcdInitialCluster field.
func (o *EtcdAPIMemberJoinOutput) SetEtcdInitialCluster(v string) {
	o.EtcdInitialCluster = &v
}

func (o EtcdAPIMemberJoinOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EtcdAPIMemberJoinOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EtcdInitialCluster) {
		toSerialize["etcdInitialCluster"] = o.EtcdInitialCluster
	}
	return toSerialize, nil
}

type NullableEtcdAPIMemberJoinOutput struct {
	value *EtcdAPIMemberJoinOutput
	isSet bool
}

func (v NullableEtcdAPIMemberJoinOutput) Get() *EtcdAPIMemberJoinOutput {
	return v.value
}

func (v *NullableEtcdAPIMemberJoinOutput) Set(val *EtcdAPIMemberJoinOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableEtcdAPIMemberJoinOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableEtcdAPIMemberJoinOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEtcdAPIMemberJoinOutput(val *EtcdAPIMemberJoinOutput) *NullableEtcdAPIMemberJoinOutput {
	return &NullableEtcdAPIMemberJoinOutput{value: val, isSet: true}
}

func (v NullableEtcdAPIMemberJoinOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEtcdAPIMemberJoinOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
