/*
gravity

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.27.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TypesAPIMetricsGetOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TypesAPIMetricsGetOutput{}

// TypesAPIMetricsGetOutput struct for TypesAPIMetricsGetOutput
type TypesAPIMetricsGetOutput struct {
	Records []TypesAPIMetricsRecord `json:"records"`
}

type _TypesAPIMetricsGetOutput TypesAPIMetricsGetOutput

// NewTypesAPIMetricsGetOutput instantiates a new TypesAPIMetricsGetOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTypesAPIMetricsGetOutput(records []TypesAPIMetricsRecord) *TypesAPIMetricsGetOutput {
	this := TypesAPIMetricsGetOutput{}
	this.Records = records
	return &this
}

// NewTypesAPIMetricsGetOutputWithDefaults instantiates a new TypesAPIMetricsGetOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTypesAPIMetricsGetOutputWithDefaults() *TypesAPIMetricsGetOutput {
	this := TypesAPIMetricsGetOutput{}
	return &this
}

// GetRecords returns the Records field value
// If the value is explicit nil, the zero value for []TypesAPIMetricsRecord will be returned
func (o *TypesAPIMetricsGetOutput) GetRecords() []TypesAPIMetricsRecord {
	if o == nil {
		var ret []TypesAPIMetricsRecord
		return ret
	}

	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TypesAPIMetricsGetOutput) GetRecordsOk() ([]TypesAPIMetricsRecord, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// SetRecords sets field value
func (o *TypesAPIMetricsGetOutput) SetRecords(v []TypesAPIMetricsRecord) {
	o.Records = v
}

func (o TypesAPIMetricsGetOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TypesAPIMetricsGetOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Records != nil {
		toSerialize["records"] = o.Records
	}
	return toSerialize, nil
}

func (o *TypesAPIMetricsGetOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTypesAPIMetricsGetOutput := _TypesAPIMetricsGetOutput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTypesAPIMetricsGetOutput)

	if err != nil {
		return err
	}

	*o = TypesAPIMetricsGetOutput(varTypesAPIMetricsGetOutput)

	return err
}

type NullableTypesAPIMetricsGetOutput struct {
	value *TypesAPIMetricsGetOutput
	isSet bool
}

func (v NullableTypesAPIMetricsGetOutput) Get() *TypesAPIMetricsGetOutput {
	return v.value
}

func (v *NullableTypesAPIMetricsGetOutput) Set(val *TypesAPIMetricsGetOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableTypesAPIMetricsGetOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableTypesAPIMetricsGetOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTypesAPIMetricsGetOutput(val *TypesAPIMetricsGetOutput) *NullableTypesAPIMetricsGetOutput {
	return &NullableTypesAPIMetricsGetOutput{value: val, isSet: true}
}

func (v NullableTypesAPIMetricsGetOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTypesAPIMetricsGetOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
