name: Build (Tag)

on:
  push:
    tags:
      - v*

permissions:
  packages: write
  # Required to create relases
  contents: write
  pull-requests: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      packages: write
      # Required to create relases
      contents: write
      pull-requests: read
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: vars
        run: make ci--env
      - id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          flavor: |
            latest=false
          tags: |
            type=raw,value=v${{ steps.vars.outputs.version }}
      - uses: docker/build-push-action@v6.11.0
        id: push
        with:
          tags: |
            ghcr.io/beryju/gravity:stable
            ghcr.io/beryju/gravity:v${{ steps.vars.outputs.version }}
          push: true
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: |
            BUILD=${{ steps.vars.outputs.build }}
            GIT_BUILD_HASH=release
          labels: ${{ steps.meta.outputs.labels }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/beryju/gravity
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      - uses: actions/create-release@v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.vars.outputs.version }}
          draft: true
          prerelease: false
          body: |
            Upgrade to this version of gravity by using this container image:

            ```
            ghcr.io/beryju/gravity:v${{ steps.vars.outputs.version }}
            ```

            Upgrade to the current JS API Client using

            ```
            npm i gravity-api@${{ steps.vars.outputs.version }}
            ```

            Upgrade to the current Golang API Client using

            ```
            go get beryju.io/gravity@v${{ steps.vars.outputs.version }}
            ```
  build-cli:
    name: Build CLI
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, amd64]
        os: [darwin, linux]
    steps:
      - uses: actions/checkout@v4
      - run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} make bin/gravity-cli
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build.outputs.release_upload_url }}
          asset_path: ./bin/gravity-cli
          asset_name: gravity-cli_${{ matrix.os }}_${{ matrix.arch }}
          asset_content_type: application/octet-stream
