name: Build (Tag)

on:
  push:
    tags:
      - v*

permissions:
  packages: write
  # Required to create relases
  contents: write
  pull-requests: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: vars
        run: make ci--env
      - uses: docker/build-push-action@v4.2.1
        with:
          tags: |
            ghcr.io/beryju/gravity:stable
            ghcr.io/beryju/gravity:v${{ steps.vars.outputs.version }}
          push: true
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: |
            BUILD=${{ steps.vars.outputs.build }}
            GIT_BUILD_HASH=${{ steps.vars.outputs.sha }}
      - uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.vars.outputs.version }}
          draft: true
          prerelease: false
          body: |
            Upgrade to this version of gravity by using this container image:

            ```
            ghcr.io/beryju/gravity:v${{ steps.vars.outputs.version }}
            ```

            Upgrade to the current JS API Client using

            ```
            npm i gravity-api@${{ steps.vars.outputs.version }}
            ```

            Upgrade to the current Golang API Client using

            ```
            go get beryju.io/gravity@v${{ steps.vars.outputs.version }}
            ```
