name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.18
      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Build web
        working-directory: web/
        run: |
          npm ci
          make -C .. gen-client-web
          npm run build
      - run: go get -v -t -d ./...
      - name: Run coverage
        run: make test-etcd-start test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: vars
        run: |
          set -x
          echo "##[set-output name=sha]$GITHUB_SHA"
          echo "##[set-output name=build]$GITHUB_RUN_ID"
          echo "##[set-output name=timestamp]$(date +%s)"
      - name: Setup node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      - name: Build web
        working-directory: web/
        run: |
          npm ci
          make -C .. gen-client-web
          npm run build
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.1.1
        with:
          tags: |
            ghcr.io/beryju/gravity:latest
            ghcr.io/beryju/gravity:dev
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: |
            BUILD=${{ steps.vars.outputs.build }}
            GIT_BUILD_HASH=${{ steps.vars.outputs.sha }}
